INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('08', DEFAULT, 'Акшинский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('06', DEFAULT, 'Александрово-Заводский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('09', DEFAULT, 'Балейский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('10', DEFAULT, 'Борзинский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('11', DEFAULT, 'Газимуро-Заводский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('13', DEFAULT, 'Забайкальский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('14', DEFAULT, 'Каларский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('15', DEFAULT, 'Калганский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('16', DEFAULT, 'Карымский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('18', DEFAULT, 'Краснокаменский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('17', DEFAULT, 'Красночикойский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('19', DEFAULT, 'Кыринский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('20', DEFAULT, 'Могочинский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('22', DEFAULT, 'Нерчинский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('23', DEFAULT, 'Нерчинско-Заводский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('24', DEFAULT, 'Оловяннинский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('25', DEFAULT, 'Ононский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('26', DEFAULT, 'Петровск-Забайкальский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('27', DEFAULT, 'Приаргунский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('28', DEFAULT, 'Сретенский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('N', DEFAULT, 'Тунгиро-Олёкминский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('30', DEFAULT, 'Тунгокоченский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('31', DEFAULT, 'Улётовский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('35', DEFAULT, 'Хилокский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('32', DEFAULT, 'Чернышевский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('01', DEFAULT, 'Читинский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('33', DEFAULT, 'Шелопугинский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('34', DEFAULT, 'Шилкинский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('02', DEFAULT, 'Дульдургинский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('03', DEFAULT, 'Могойтуйского');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('21', DEFAULT, 'Агинский');

INSERT INTO DEVICES_CONTROL.ROLES (ID, DESCRIPTION, NAME)
VALUES (DEFAULT, 'Администратор', 'Role_Admin');

INSERT INTO DEVICES_CONTROL.ROLES (ID, DESCRIPTION, NAME)
VALUES (DEFAULT, 'Пользователь', 'Role_User');
