INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('08', DEFAULT, 'Акшинский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('06', DEFAULT, 'Александрово-Заводский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('09', DEFAULT, 'Балейский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('10', DEFAULT, 'Борзинский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('11', DEFAULT, 'Газимуро-Заводский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('13', DEFAULT, 'Забайкальский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('14', DEFAULT, 'Каларский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('15', DEFAULT, 'Калганский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('16', DEFAULT, 'Карымский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('18', DEFAULT, 'Краснокаменский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('17', DEFAULT, 'Красночикойский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('19', DEFAULT, 'Кыринский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('20', DEFAULT, 'Могочинский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('22', DEFAULT, 'Нерчинский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('23', DEFAULT, 'Нерчинско-Заводский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('24', DEFAULT, 'Оловяннинский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('25', DEFAULT, 'Ононский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('26', DEFAULT, 'Петровск-Забайкальский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('27', DEFAULT, 'Приаргунский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('28', DEFAULT, 'Сретенский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('N', DEFAULT, 'Тунгиро-Олёкминский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('30', DEFAULT, 'Тунгокоченский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('31', DEFAULT, 'Улётовский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('35', DEFAULT, 'Хилокский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('32', DEFAULT, 'Чернышевский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('01', DEFAULT, 'Читинский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('33', DEFAULT, 'Шелопугинский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('34', DEFAULT, 'Шилкинский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('02', DEFAULT, 'Дульдургинский');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('03', DEFAULT, 'Могойтуйского');
INSERT INTO DEVICES_CONTROL.REGIONS (CODE, ID, NAME)
VALUES ('21', DEFAULT, 'Агинский');

INSERT INTO DEVICES_CONTROL.ROLES (ID, DESCRIPTION, NAME)
VALUES (DEFAULT, 'Администратор', 'ROLE_Admin');
INSERT INTO DEVICES_CONTROL.ROLES (ID, DESCRIPTION, NAME)
VALUES (DEFAULT, 'Пользователь', 'ROLE_User');

INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (1,'Акша','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (1,'Бытэв','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (1,'Дорожное','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (1,'Курулга','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (1,'Могойтуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (1,'Нарасун','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (1,'Новоказачинск','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (1,'Новокургатай','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (1,'Орой','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (1,'Такеча','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (1,'Тохтор','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (1,'Убур-Тохтор','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (1,'Улача','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (1,'Урейск','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (1,'Усть-Иля','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (2,'Александровский Завод','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (2,'Базаново','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (2,'Бохто','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (2,'Бутунтай','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (2,'Васильевский Хутор','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (2,'Верхний Аленуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (2,'Журавлёво','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (2,'Кириллиха','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (2,'Клин','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (2,'Кокуй 1-й','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (2,'Кокуй 2-й','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (2,'Красноярово','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (2,'Кузнецово','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (2,'Кутугай','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (2,'Манкечур','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (2,'Маньково','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (2,'Мулино','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (2,'Николаевка','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (2,'Новый Акатуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (2,'Онон-Борзя','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (2,'Почекуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (2,'Савво-Борзя','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (2,'Старый Акатуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (2,'Чиндагатай','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (2,'Шара','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (2,'Шаракан','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (2,'Шаранча','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (3,'Алия','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (3,'Балей','город');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (3,'Барановск','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (3,'Большое Казаково','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (3,'Бочкарёво','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (3,'Буторино','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (3,'Верхний Кокуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (3,'Гробово','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (3,'Джида','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (3,'Ёлкино','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (3,'Жетково','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (3,'Жидка','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (3,'Журавлёво','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (3,'Казаковский Промысел','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (3,'Колобово','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (3,'Лесково','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (3,'Лесоучасток Саранная','населённый пункт');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (3,'Ложниково','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (3,'Ложниково','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (3,'Матусово','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (3,'Нижнее Гирюнино','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (3,'Нижний Ильдикан','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (3,'Нижний Кокуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (3,'Новоивановка','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (3,'Онохово','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (3,'Подойницыно','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (3,'Рудник Жетково','населённый пункт');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (3,'Сарбактуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (3,'Унда','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (3,'Ундино-Поселье','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (3,'Ургучан','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (3,'Усть-Ягьё','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (4,'Акурай','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (4,'Биликтуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (4,'Борзя','город');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (4,'Зун-Торей','разъезд');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (4,'Ключевское','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (4,'Кондуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (4,'Контой','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (4,'Курунзулай','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (4,'Малый Соловьёвск','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (4,'Малый Хада-Булак','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (4,'Новоборзинское','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (4,'Олдонда','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (4,'Передняя Бырка','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (4,'Приозёрное','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (4,'Соктуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (4,'Соловьёвск','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (4,'Тасырхой','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (4,'Усть-Озёрная','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (4,'Хада-Булак','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (4,'Цаган-Олуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (4,'Чемусово','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (4,'Чиндант 2-й','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (4,'Шерловая Гора','пгт');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (4,'Шоноктуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (4,'Юбилейное','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (4,'Южное','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (5,'Батакан','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (5,'Будюмкан','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (5,'Бура','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (5,'Бурукан','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (5,'Верхнее Солонечное','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (5,'Газимурские Кавыкучи','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (5,'Газимурский Завод','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (5,'Догьё','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (5,'Закаменная','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (5,'Зерен','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (5,'Игдоча','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (5,'Кактолга','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (5,'Калдага','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (5,'Корабль','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (5,'Кунгара','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (5,'Курлея','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (5,'Курюмдюкан','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (5,'Луговское','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (5,'Новоширокинский','посёлок');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (5,'Новый Батакан','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (5,'Павловск','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (5,'Рудник Солонечный','населённый пункт');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (5,'Солонцы','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (5,'Тайна','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (5,'Трубачёво','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (5,'Урюпино','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (5,'Ушмун','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (5,'Хайкан','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (5,'Широкая','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (5,'Ямкун','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (6,'Абагайтуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (6,'Арабатук','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (6,'Билитуй','посёлок при станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (6,'Даурия','посёлок при станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (6,'Забайкальск','пгт');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (6,'Красный Великан','посёлок');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (6,'Мациевская','посёлок при станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (6,'Рудник Абагайтуй','населённый пункт');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (6,'Семиозёрье','посёлок');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (6,'Степной','посёлок');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (6,'Харанор','посёлок при станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (7,'Икабья','посёлок при станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (7,'Куанда','посёлок при станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (7,'Кюсть-Кемда','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (7,'Неляты','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (7,'Новая Чара','пгт');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (7,'Средний Калар','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (7,'Удокан','посёлок');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (7,'Чапо-Олого','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (7,'Чара','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (8,'Бура','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (8,'Бура 1-я','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (8,'Верхний Калгукан','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (8,'Доно','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (8,'Доно 1-е','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (8,'Запокровский','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (8,'Кадая','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (8,'Кадая 1-я','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (8,'Калга','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (8,'Козлово','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (8,'Нижний Калгукан','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (8,'Нижний Калгукан 1-й','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (8,'Средняя Борзя','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (8,'Чингильтуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (8,'Чупрово','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (8,'Шивия','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (9,'Адриановка','посёлок станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (9,'Атамановка','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (9,'Большая Тура','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (9,'Верхняя Талача','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (9,'Дарасун','пгт');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (9,'Жимбира','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (9,'Зубковщина','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (9,'Кадахта','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (9,'Кайдалово','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (9,'Каланга','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (9,'Карымское','пгт');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (9,'Кумахта','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (9,'Курорт-Дарасун','пгт');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (9,'Маяки','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (9,'Нарын-Талача','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (9,'Новодоронинск','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (9,'Олентуй','посёлок');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (9,'Подлесное','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (9,'Поселье','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (9,'Северная Кадахта','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (9,'Седловая','посёлок станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (9,'Солонцово','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (9,'Средняя Талача','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (9,'Тарская','посёлок станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (9,'Тыргетуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (9,'Урульга','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (9,'Усть-Нацигун','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (9,'Шара-Горохон','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (10,'Арамогойтуй','посёлок при станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (10,'Богдановка','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (10,'Брусиловка','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (10,'Кайластуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (10,'Капцегайтуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (10,'Ковыли','посёлок');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (10,'Краснокаменск','город');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (10,'Куйтун','посёлок');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (10,'Маргуцек','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (10,'Соктуй-Милозан','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (10,'Среднеаргунск','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (10,'Урулюнгуй','посёлок при станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (10,'Целинный','посёлок');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (10,'Юбилейный','посёлок');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (11,'Александровка','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (11,'Альбитуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (11,'Архангельское','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (11,'Афонькино','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (11,'Аца','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (11,'Байхор','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (11,'Барахоево','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (11,'Большаково','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (11,'Большая Речка','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (11,'Бурсомон','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (11,'Быково','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (11,'Верхний Шергольджин','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (11,'Гремяча','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (11,'Гутай','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (11,'Жиндо 1-е','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (11,'Жиндо 2-е','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (11,'Жиндокон','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (11,'Захарово','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (11,'Зашулан','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (11,'Конкино','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (11,'Коротково','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (11,'Котый','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (11,'Красные Речки','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (11,'Красный Чикой','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (11,'Малоархангельск','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (11,'Маргинтуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (11,'Менза','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (11,'Могзон','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (11,'Мостовка','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (11,'Нижний Нарым','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (11,'Осиновка','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (11,'Прииск Большая Речка','населённый пункт');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (11,'Семиозёрье','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (11,'Средний Шергольджин','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (11,'Стеклозавод','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (11,'Укыр','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (11,'Урлук','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (11,'Усть-Урлук','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (11,'Усть-Ямаровка','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (11,'Фомичёво','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (11,'Хилкотой','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (11,'Черемхово','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (11,'Шимбилик','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (11,'Шонуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (11,'Этытэй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (11,'Ядрихино','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (11,'Ямаровка','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (12,'Алтан','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (12,'Билютуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (12,'Букукун','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (12,'Былыра','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (12,'Верхний Стан','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (12,'Верхний Ульхун','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (12,'Гавань','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (12,'Кыра','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (12,'Любовь','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (12,'Мангут','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (12,'Михайло-Павловск','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (12,'Мордой','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (12,'Надёжный','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (12,'Нижний Стан','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (12,'Тарбальджей','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (12,'Турген','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (12,'Тырин','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (12,'Ульхун-Партия','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (12,'Устье','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (12,'Хапчеранга','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (12,'Шумунда','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (13,'Амазар','пгт');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (13,'Аникино','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (13,'Артеушка','посёлок при станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (13,'Блок-Пост Красавка','посёлок при станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (13,'Блок-Пост Потайка','посёлок при станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (13,'Блок-Пост Тетёркин Ключ','посёлок при станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (13,'Блок-Пост Утени','посёлок при станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (13,'Германовский','посёлок при станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (13,'Горький','посёлок');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (13,'Давенда','пгт');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (13,'Джелонда','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (13,'Жанна','посёлок при станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (13,'Итака','пгт');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (13,'Кендагиры','посёлок при станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (13,'Кислый Ключ','посёлок при станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (13,'Ключевский','пгт');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (13,'Колокольный','посёлок при станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (13,'Ксеньевка','пгт');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (13,'Кудеча','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (13,'Малоковали','посёлок при станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (13,'Могоча','город');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (13,'Нанагры','посёлок при станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (13,'Пеньковая','посёлок при станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (13,'Покровка','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (13,'Раздольное','посёлок при станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (13,'Сбега','посёлок при станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (13,'Семиозёрный','посёлок при станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (13,'Таптугары','посёлок при станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (13,'Тёмная','посёлок при станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (13,'Чалдонка','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (13,'Часовая','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (13,'Чичатка','посёлок при станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (14,'Алеур','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (14,'Андронниково','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (14,'Апрелково','посёлок при станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (14,'Беломестново','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (14,'Берёзово','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (14,'Бишигино','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (14,'Большой Луг','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (14,'Борщовка','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (14,'Верхние Ключи','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (14,'Верхний Умыкэй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (14,'Волочаевка','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (14,'Заречный','посёлок');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (14,'Знаменка','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (14,'Зюльзикан','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (14,'Зюльзя','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (14,'Илим','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (14,'Калинино','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (14,'Кангил','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (14,'Котельниково','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (14,'Крупянка','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (14,'Кулаково','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (14,'Левые Кумаки','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (14,'Макеевка','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (14,'Нагорный','посёлок');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (14,'Нерчинск','город');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (14,'Нижние Ключи','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (14,'Олекан','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (14,'Олинск','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (14,'Пешково','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (14,'Право-Пешково','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (14,'Правые Кумаки','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (14,'Приисковый','пгт');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (14,'Савватеево','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (14,'Северная Знаменка','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (14,'Сенная','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (14,'Шивки','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (15,'Аргунск','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (15,'Байка','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (15,'Большой Зерентуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (15,'Булдуруй 1-й','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (15,'Булдуруй 2-й','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (15,'Георгиевка','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (15,'Горбуновка','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (15,'Горный Зерентуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (15,'Домасово','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (15,'Золотоноша','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (15,'Ивановка','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (15,'Ишага','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (15,'Михайловка','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (15,'Михайловский Участок','посёлок');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (15,'Нерчинский Завод','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (15,'Олочи','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (15,'Поперечный Зерентуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (15,'Солонечная','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (15,'Средняя','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (15,'Уровские Ключи','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (15,'Чалбучи-Килга','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (15,'Чашино-Ильдикан','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (15,'Широкая','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (15,'Явленка','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (16,'Антия','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (16,'Аренда','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (16,'Безречная','посёлок при станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (16,'Булум','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (16,'Бурулятуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (16,'Бырка','посёлок при станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (16,'Верхний Ононск','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (16,'Верхний Шаранай','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (16,'Верхняя Турга','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (16,'Восточная Долгокыча','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (16,'Восточный Бурулятуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (16,'Долгокыча','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (16,'Единение','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (16,'Заря','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (16,'Золотореченск','пгт');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (16,'Калангуй','пгт');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (16,'Караксар','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (16,'Ключевая','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (16,'Комкай','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (16,'Кулинда','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (16,'Маяк','посёлок');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (16,'Мирная','посёлок при станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (16,'Нижний Улятуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (16,'Оловорудник','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (16,'Оловянная','пгт');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (16,'Ононск','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (16,'Победа','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (16,'Средний Шаранай','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (16,'Степь','посёлок при станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (16,'Тополёвка','посёлок');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (16,'Турга','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (16,'Улан-Цацык','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (16,'Улятуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (16,'Уртуйский','посёлок');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (16,'Хада-Булак','посёлок при станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (16,'Хара-Бырка','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (16,'Центральный Хада-Булак','посёлок');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (16,'Шивия','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (16,'Ясная','посёлок при станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (16,'Ясногорск','пгт');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (17,'Байн-Цаган','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (17,'Большевик','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (17,'Буйлэсан','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (17,'Верхний Цасучей','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (17,'Заря','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (17,'Икарал','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (17,'Красная Ималка','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (17,'Кубухай','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (17,'Кулусутай','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (17,'Куранжа','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (17,'Нижний Кулусутай','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (17,'Нижний Цасучей','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (17,'Новая Заря','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (17,'Новый Дурулгуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (17,'Старый Дурулгуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (17,'Старый Чиндант','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (17,'Тут-Халтуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (17,'Урта-Харгана','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (17,'Усть-Борзя','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (17,'Усть-Ималка','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (17,'Усть-Лиска','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (17,'Холуй-База','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (17,'Чиндант 1-й','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (18,'Алентуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (18,'Баляга','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (18,'Баляга-Катангар','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (18,'Голяткино','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (18,'Зугмара','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (18,'Кандобаево','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (18,'Катаево','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (18,'Катангар','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (18,'Красная Долина','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (18,'Кукун','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (18,'Кули','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (18,'Лесоучасток Катангар','населённый пункт');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (18,'Малета','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (18,'Нижний Тарбагатай','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (18,'Новая Зардама','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (18,'Новоникольское','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (18,'Новопавловка','пгт');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (18,'Новопавловское','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (18,'Обор','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (18,'Орсук','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (18,'Пески','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (18,'Петровск-Забайкальский','город');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (18,'Сохотой','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (18,'Старая Зардама','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (18,'Тарбагатай','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (18,'Толбага','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (18,'Усть-Обор','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (18,'Харауз','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (18,'Хохотуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (19,'Бырка','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (19,'Верея','посёлок');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (19,'Верхний Тасуркай','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (19,'Восточный Досатуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (19,'Горда','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (19,'Досатуй','посёлок');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (19,'Дурой','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (19,'Дурой 1-й','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (19,'Зоргол','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (19,'Кличка','пгт');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (19,'Кути','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (19,'Молодёжный','посёлок');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (19,'Нижний Зоргол','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (19,'Новая Бырка','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (19,'Новое Погадаево','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (19,'Новоивановка','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (19,'Новоцурухайтуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (19,'Норинск','посёлок');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (19,'Погадаево','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (19,'Пограничный','посёлок');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (19,'Пограничный 1-й','посёлок');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (19,'Приаргунск','пгт');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (19,'Селинда','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (19,'Станция-Досатуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (19,'Староцурухайтуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (19,'Староцурухайтуй 1-й','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (19,'Талман-Борзя','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (19,'Улан','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (19,'Урулюнгуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (19,'Урулюнгуй 1-й','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (19,'Усть-Тасуркай','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (20,'3','разъезд');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (20,'Адом','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (20,'Алия','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (20,'Аргун','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (20,'Баян','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (20,'Болотово','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (20,'Большие Боты','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (20,'Бори','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (20,'Верхние Куларки','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (20,'Верхняя Куэнга','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (20,'Горбица','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (20,'Делюн','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (20,'Дом Отдыха Чалбучи','населённый пункт');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (20,'Дунаево','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (20,'Ералга','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (20,'Кокертай','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (20,'Кокуй','пгт');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (20,'Кудея','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (20,'Кулан','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (20,'Ломы','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (20,'Лужанки','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (20,'Мангидай','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (20,'Молодовск','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (20,'Моргул','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (20,'Мыгжа','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (20,'Наринзор','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (20,'Нижние Куларки','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (20,'Нижняя Алия','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (20,'Нижняя Куэнга','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (20,'Сретенск','город');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (20,'Старолончаково','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (20,'Уктыча','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (20,'Усть-Карск','пгт');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (20,'Усть-Курлыч','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (20,'Усть-Наринзор','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (20,'Усть-Начин','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (20,'Усть-Чёрная','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (20,'Фирсово','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (20,'Фирсово 1-е','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (20,'Чалбучи','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (20,'Чикичей','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (20,'Шапка','разъезд');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (20,'Шеметово','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (20,'Шилкинский Завод','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (21,'Гуля','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (21,'Заречное','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (21,'Моклакан','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (21,'Средняя Олёкма','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (21,'Тупик','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (22,'Акима','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (22,'Бутиха','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (22,'Верх-Усугли','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (22,'Вершино-Дарасунский','пгт');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (22,'Зелёное Озеро','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (22,'Красный Яр','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (22,'Кыкер','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (22,'Нижний Стан','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (22,'Светлый','посёлок');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (22,'Сухайтуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (22,'Тунгокочен','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (22,'Ульдурга','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (22,'Усть-Каренга','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (22,'Усугли','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (22,'Халтуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (22,'Цагакшино','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (22,'Юмурчен','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (23,'Аблатуйский Бор','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (23,'Аблатукан','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (23,'Арей','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (23,'Арта','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (23,'Бальзой','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (23,'Голубичная','посёлок при станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (23,'Горека','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (23,'Горекацан','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (23,'Горный','пгт');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (23,'Дешулан','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (23,'Доронинское','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (23,'Дровяная','пгт');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (23,'Красная Речка','посёлок');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (23,'Ленинский','посёлок');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (23,'Николаевское','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (23,'Новосалия','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (23,'Новые Ключи','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (23,'Стародоронинское','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (23,'Старый Ленинск','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (23,'Танга','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (23,'Татаурово','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (23,'Улёты','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (23,'Хадакта','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (23,'Черемхово','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (23,'Шебартуй 2-й','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (23,'Шехолан','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (24,'Алентуйка','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (24,'Аренур','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (24,'Бада','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (24,'Глинка','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (24,'Гыршелун','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (24,'Дайгур','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (24,'Жилкин Хутор','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (24,'Жипхеген','посёлок при станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (24,'Загарино','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (24,'Закульта','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (24,'Зурун','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (24,'Линёво Озеро','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (24,'Могзон','пгт');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (24,'Мухор-Шибирка','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (24,'Сарантуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (24,'Сосновка','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (24,'Тайдут','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (24,'Тэрэпхэн','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (24,'Укурик','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (24,'Улётка','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (24,'Улястуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (24,'Ушоты','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (24,'Харагун','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (24,'Харагун-Саранка','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (24,'Хилогосон','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (24,'Хилок','город');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (24,'Хушенга','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (24,'Центральный Харагун','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (24,'Шиля','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (24,'Энгорок','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (25,'Аксёново-Зиловское','пгт');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (25,'Алеур','посёлок при станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (25,'Алеур','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (25,'Алеур 1-й','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (25,'Алеур 2-й','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (25,'Ареда','посёлок при станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (25,'Арчикой','посёлок при станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (25,'Багульный','посёлок');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (25,'Байгул','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (25,'Бородинск','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (25,'Букачача','пгт');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (25,'Бухта','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (25,'Бушулей','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (25,'Гаур','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (25,'Жирекен','пгт');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (25,'Зудыра','посёлок при станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (25,'Икшица','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (25,'Кадая','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (25,'Ковекта','посёлок при станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (25,'Комсомольское','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (25,'Кумаканда','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (25,'Курлыч','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (25,'Мильгидун','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (25,'Налгекан','посёлок при станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (25,'Нижний Мильгидун','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (25,'Новоильинск','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (25,'Новый Олов','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (25,'Озёрная','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (25,'Посельское','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (25,'Станция-Укурей','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (25,'Старый Олов','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (25,'Сухой Байгул','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (25,'Укурей','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (25,'Улей','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (25,'Ульякан','посёлок при станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (25,'Урюм','посёлок при станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (25,'Усть-Горбица','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (25,'Утан','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (25,'Чернышевск','пгт');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (25,'Шивия-Наделяево','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (25,'Щебёночный Завод','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Авдей','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Александровка','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Амодово','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Арахлей','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Атамановка','пгт');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Беклемишево','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Береговой','посёлок');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Бургень','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Верх-Нарым','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Верхняя Карповка','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Верх-Чита','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Гонгота','посёлок станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Дом Инвалидов','посёлок');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Домна','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Домно-Ключи','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Елизаветино','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Ерёмино','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Жипковщина','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Забайкальский','посёлок');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Заречное','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Засопка','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Иван-Озеро','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Ильинка','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Ингода','посёлок станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Иргень','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Каменка','посёлок');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Карповка','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Колочное 1-е','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Колочное 2-е','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Кука','посёлок станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Кука','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Ленинский','посёлок');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Лесная','посёлок станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Лесной Городок','посёлок');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Лесоучасток Верх-Нарым','населённый пункт');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Маккавеево','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Мухор-Кондуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Новая Кука','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Новое Сивяково','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Новокручининский','пгт');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Новотроицк','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Оленгуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Подволок','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Преображенка','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Ручейки','посёлок');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Сивяково','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Смоленка','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Сохондо','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Старая Кука','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Сыпчегур','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Танха','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Тасей','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Тургутуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Угдан','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Хвойный','посёлок');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Черново','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Чита','город');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Шакша','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Шишкино','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Яблоново','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (26,'Ягодный','посёлок');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (27,'Банщиково','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (27,'Богданово','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (27,'Большой Тонтой','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (27,'Верхний Тергень','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (27,'Верх-Ягьё','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (27,'Вершино-Шахтаминский','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (27,'Глинянка','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (27,'Дая','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (27,'Даякон','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (27,'Деревцово','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (27,'Ишикан','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (27,'Копунь','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (27,'Купряково','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (27,'Малый Тонтой','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (27,'Малышево','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (27,'Мироново','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (27,'Некрасово','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (27,'Нижняя Шахтама','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (27,'Селекционная','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (27,'Сивачи','посёлок');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (27,'Средняя Шахтама','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (27,'Ундинские Кавыкучи','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (27,'Чонгуль','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (27,'Шелопугино','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (27,'Шивия','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (28,'Апрелково','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (28,'Арбагар','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (28,'Байцетуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (28,'Берея','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (28,'Богомягково','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (28,'Васильевка','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (28,'Верхний Теленгуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (28,'Верхняя Хила','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (28,'Галкино','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (28,'Золотухино','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (28,'Зубарево','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (28,'Казаново','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (28,'Кибасово','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (28,'Кироча','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (28,'Кокуй-Комогорцево','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (28,'Красноярово','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (28,'Кыэкен','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (28,'Макарово','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (28,'Мирсаново','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (28,'Митрофаново','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (28,'Нижнее Галкино','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (28,'Нижнее Номоконово','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (28,'Нижняя Хила','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (28,'Новоберёзовское','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (28,'Новое','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (28,'Номоконово','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (28,'Онон','посёлок при станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (28,'Ононское','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (28,'Островки','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (28,'Первомайский','пгт');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (28,'Размахнино','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (28,'Саввино','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (28,'Солнцево','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (28,'Средняя Кия','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (28,'Ульяновка','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (28,'Уненкер','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (28,'Усть-Ага','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (28,'Усть-Ножовая','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (28,'Усть-Теленгуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (28,'Холбон','пгт');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (28,'Чирон','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (28,'Шиванда','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (28,'Шилка','город');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (31,'Агинское','пгт');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (31,'Амитхаша','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (31,'Аргалей','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (31,'Баян-Булак','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (31,'Будулан','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (31,'Булактуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (31,'Верхний Кункур','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (31,'Верхняя Салия','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (31,'Восточная Амитхаша','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (31,'Гунэй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (31,'Дэлбэрхэй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (31,'Занта','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (31,'Западный Будулан','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (31,'Заречный Челутай','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (31,'Кункур','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (31,'Лаха','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (31,'Лесозавод','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (31,'Новоорловск','пгт');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (31,'Орловский','пгт');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (31,'Пунцук','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (31,'Сахюрта','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (31,'Судунтуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (31,'Урда-Ага','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (31,'Хойто-Ага','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (31,'Хусатуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (31,'Цокто-Хангил','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (31,'Цугол','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (31,'Челутай','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (31,'Южный Аргалей','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (30,'Ага','посёлок при станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (30,'Ага-Хангил','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (30,'Ара-Булак','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (30,'Бильчиртуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (30,'Боржигантай','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (30,'Булак','посёлок при станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (30,'Бурятская','посёлок при станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (30,'Верхняя Ага','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (30,'Гомбын-Хунды','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (30,'Догой','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (30,'Ерама','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (30,'Западный Ушарбай','хутор');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (30,'Зугалай','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (30,'Зунор','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (30,'Известковое','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (30,'Курильжа','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (30,'Кусочи','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (30,'Могойтуй','пгт');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (30,'Нарин','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (30,'Нижняя Ага','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (30,'Новый Ушарбай','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (30,'Нуринск','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (30,'Ортуй','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (30,'Остречная','посёлок при станции');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (30,'Перевал','разъезд');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (30,'67','разъезд');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (30,'69','разъезд');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (30,'71','разъезд');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (30,'Толон','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (30,'Улан-Сарта','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (30,'Уронай','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (30,'Усть-Нарин','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (30,'Ушарбай','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (30,'Хайласан','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (30,'Хара-Шибирь','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (30,'Харганаша','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (30,'Цаган-Ола','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (30,'Цаган-Челутай','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (30,'Цугол','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (29,'Алханай','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (29,'Ара-Иля','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (29,'Бальзино','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (29,'Бурал','хутор');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (29,'Верхний Таптанай','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (29,'Восточный Зуткулей','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (29,'Восточный Токчин','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (29,'Дульдурга','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (29,'Западный Токчин','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (29,'Западный Узон','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (29,'Зуткулей','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (29,'Иля','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (29,'Красноярово','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (29,'Новый Чиндалей','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (29,'Северный Алханай','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (29,'Северный Зуткулей','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (29,'Северный Узон','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (29,'Старый Чиндалей','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (29,'Таптанай','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (29,'Токчин','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (29,'Узон','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (29,'Чиндалей','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (29,'Южный Алханай','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (29,'Южный Зуткулей','село');
INSERT INTO DEVICES_CONTROL.SETTLEMENTS (ID_REGION,NAME,"TYPE")
VALUES (29,'Южный Узон','село');

INSERT INTO DEVICES_CONTROL.ADDRESS (ID_SETTLEMENTS,HOUSE,STREET)
VALUES (711,'160Б','ул.Чкалова');
INSERT INTO DEVICES_CONTROL.ADDRESS (ID_SETTLEMENTS,HOUSE,STREET)
VALUES (711,'160','ул.Чкалова');
INSERT INTO DEVICES_CONTROL.ADDRESS (ID_SETTLEMENTS,HOUSE,STREET)
VALUES (711,'32','ул.Чайковского');
INSERT INTO DEVICES_CONTROL.ADDRESS (ID_SETTLEMENTS,HOUSE,STREET)
VALUES (711,'72','ул.Бутина');
INSERT INTO DEVICES_CONTROL.ADDRESS (ID_SETTLEMENTS,HOUSE,STREET)
VALUES (783,'31','ул.Ленина');
INSERT INTO DEVICES_CONTROL.ADDRESS (ID_SETTLEMENTS,HOUSE,STREET)
VALUES (783,'2 (литер А)','ул.Богомягкова');
INSERT INTO DEVICES_CONTROL.ADDRESS (ID_SETTLEMENTS,HOUSE,STREET)
VALUES (783,'2 (литер Б)','ул.Богомягкова');
INSERT INTO DEVICES_CONTROL.ADDRESS (ID_SETTLEMENTS,HOUSE,STREET)
VALUES (783,'2 (литер В)','ул.Богомягкова');
INSERT INTO DEVICES_CONTROL.ADDRESS (ID_SETTLEMENTS,HOUSE,STREET)
VALUES (44,'26','ул.Советская');
INSERT INTO DEVICES_CONTROL.ADDRESS (ID_SETTLEMENTS,HOUSE,STREET)
VALUES (77,'52 А','ул.Ленина');
INSERT INTO DEVICES_CONTROL.ADDRESS (ID_SETTLEMENTS,HOUSE,STREET)
VALUES (201,'505','');
INSERT INTO DEVICES_CONTROL.ADDRESS (ID_SETTLEMENTS,HOUSE,STREET)
VALUES (297,'13','ул.Комсомольская');
INSERT INTO DEVICES_CONTROL.ADDRESS (ID_SETTLEMENTS,HOUSE,STREET)
VALUES (297,'2','ул.Индустриальная');
INSERT INTO DEVICES_CONTROL.ADDRESS (ID_SETTLEMENTS,HOUSE,STREET)
VALUES (333,'5','ул.Шилова');
INSERT INTO DEVICES_CONTROL.ADDRESS (ID_SETTLEMENTS,HOUSE,STREET)
VALUES (453,'23 А','ул.Ключевская');
INSERT INTO DEVICES_CONTROL.ADDRESS (ID_SETTLEMENTS,HOUSE,STREET)
VALUES (521,'30','ул.Набережная');
INSERT INTO DEVICES_CONTROL.ADDRESS (ID_SETTLEMENTS,HOUSE,STREET)
VALUES (609,'5','ул.Дзержинского');
INSERT INTO DEVICES_CONTROL.ADDRESS (ID_SETTLEMENTS,HOUSE,STREET)
VALUES (16,'6','ул.Комсомольская');
INSERT INTO DEVICES_CONTROL.ADDRESS (ID_SETTLEMENTS,HOUSE,STREET)
VALUES (1,'20','ул.Партизанская');
INSERT INTO DEVICES_CONTROL.ADDRESS (ID_SETTLEMENTS,HOUSE,STREET)
VALUES (107,'28','ул.Журавлева');
INSERT INTO DEVICES_CONTROL.ADDRESS (ID_SETTLEMENTS,HOUSE,STREET)
VALUES (135,'28','ул.Железнодорожная');
INSERT INTO DEVICES_CONTROL.ADDRESS (ID_SETTLEMENTS,HOUSE,STREET)
VALUES (146,'22','ул.Магистральная');
INSERT INTO DEVICES_CONTROL.ADDRESS (ID_SETTLEMENTS,HOUSE,STREET)
VALUES (159,'3','ул.60 лет Октября');
INSERT INTO DEVICES_CONTROL.ADDRESS (ID_SETTLEMENTS,HOUSE,STREET)
VALUES (177,'24','ул.Торговый переулок');
INSERT INTO DEVICES_CONTROL.ADDRESS (ID_SETTLEMENTS,HOUSE,STREET)
VALUES (232,'150','ул.Пролетарская');
INSERT INTO DEVICES_CONTROL.ADDRESS (ID_SETTLEMENTS,HOUSE,STREET)
VALUES (263,'29','ул. Комсомольская');
INSERT INTO DEVICES_CONTROL.ADDRESS (ID_SETTLEMENTS,HOUSE,STREET)
VALUES (359,'2','ул.Булгаковой');
INSERT INTO DEVICES_CONTROL.ADDRESS (ID_SETTLEMENTS,HOUSE,STREET)
VALUES (393,'50','ул.Московская');
INSERT INTO DEVICES_CONTROL.ADDRESS (ID_SETTLEMENTS,HOUSE,STREET)
VALUES (420,'50','ул.Ленина');
INSERT INTO DEVICES_CONTROL.ADDRESS (ID_SETTLEMENTS,HOUSE,STREET)
VALUES (482,'1','ул.Воинов-Интернационалистов');
INSERT INTO DEVICES_CONTROL.ADDRESS (ID_SETTLEMENTS,HOUSE,STREET)
VALUES (543,'1 А','ул.Советская');
INSERT INTO DEVICES_CONTROL.ADDRESS (ID_SETTLEMENTS,HOUSE,STREET)
VALUES (579,'69','ул.Кирова');
INSERT INTO DEVICES_CONTROL.ADDRESS (ID_SETTLEMENTS,HOUSE,STREET)
VALUES (652,'38','ул.Центральная');
INSERT INTO DEVICES_CONTROL.ADDRESS (ID_SETTLEMENTS,HOUSE,STREET)
VALUES (739,'20','ул.Юбилейная');
INSERT INTO DEVICES_CONTROL.ADDRESS (ID_SETTLEMENTS,HOUSE,STREET)
VALUES (859,'24','ул.Лазо');
INSERT INTO DEVICES_CONTROL.ADDRESS (ID_SETTLEMENTS,HOUSE,STREET)
VALUES (830,'5','пер.Пионерский');
INSERT INTO DEVICES_CONTROL.ADDRESS (ID_SETTLEMENTS,HOUSE,STREET)
VALUES (784,'73','ул.Базара Ринчино');

INSERT INTO DEVICES_CONTROL.STATUS (DESCRIPTION,NAME,"TYPE")
VALUES ('Находится в использовании','Эксплуатируется','device');
INSERT INTO DEVICES_CONTROL.STATUS (DESCRIPTION,NAME,"TYPE")
VALUES ('Техническая или программная неисправность\Настройка нового оборудования','Настройка\Ремонт','device');
INSERT INTO DEVICES_CONTROL.STATUS (DESCRIPTION,NAME,"TYPE")
VALUES ('Находтся на складе по указанному адресу','На складе','device');
INSERT INTO DEVICES_CONTROL.STATUS (DESCRIPTION,NAME,"TYPE")
VALUES ('Находится в подразделении по указанному адресу','В подразделении','device');
INSERT INTO DEVICES_CONTROL.STATUS (DESCRIPTION,NAME,"TYPE")
VALUES ('Техника которая находится на списании','Утилизация','device');
INSERT INTO DEVICES_CONTROL.STATUS (DESCRIPTION,NAME,"TYPE")
VALUES ('Списанная техника','Утилизировано','device');

INSERT INTO DEVICES_CONTROL.DEVICES_TYPES (NAME)
VALUES ('Системный блок');
INSERT INTO DEVICES_CONTROL.DEVICES_TYPES (NAME)
VALUES ('Монитор');
INSERT INTO DEVICES_CONTROL.DEVICES_TYPES (NAME)
VALUES ('Принтер');
INSERT INTO DEVICES_CONTROL.DEVICES_TYPES (NAME)
VALUES ('Сканер');
INSERT INTO DEVICES_CONTROL.DEVICES_TYPES (NAME)
VALUES ('ИБП');
INSERT INTO DEVICES_CONTROL.DEVICES_TYPES (NAME)
VALUES ('Ноутбуки');

INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('АРРLЕ','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('SАМЅUNG','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('НР','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('DЕLL','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('LЕNОVО','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('ЅОNУ','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('МІСRОЅОFТ','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('АЅUЅ','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('LG','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('ТОЅHІВА','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('АСЕR','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('РАNАЅОNІС','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('ІВМ','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('САNОN','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('ЕРЅОN','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('ЅНАRР','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('АРРLІАNСЕЅ','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('МОTОRОLА','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('FІЅНЕR РRІСЕ','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('ВОЅСН','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('МАУTАG','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('ЅАNЅUІ','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('КЕNМОRЕ','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('iRU','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('APC','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('RDW Computers','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('Ginzzu ','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('ViewSonic','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('Kraftway','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('СВЕГА-Компьютер','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('PROVIEW','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('IRBIS ','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('Brother','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('Fujitsu','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('DEPO Computers','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('Philips','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('Xerox','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('AOC','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('Belinea','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('Avision','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('Powercool','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('Снежный Барс','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('Powercom','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('MGE','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('OKI','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('Ippon','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('Aquarius','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('Compaq','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('MUSTEK','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('Konica','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('GIGABYTE','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('BenQ','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('Avaya','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('Konica Minolta','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('R-Style Softlab','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('N-Power','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('ФилаксКом','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('FSP','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('NEC','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('Арасhе','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('ВlасkBеrrу','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('Сооlраd','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('Яндекс','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('Эльбрус','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('Ростелеком','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('Alcatel','device');
INSERT INTO DEVICES_CONTROL.MANUFACTURER (NAME,"TYPE")
	VALUES ('Архос','device');
