INSERT INTO DEVICES_CONTROL.CITY (ID, NAME)
VALUES (DEFAULT, 'г.Чита');

INSERT INTO DEVICES_CONTROL.REGIONS (CODE, CITY, ID, NAME)
VALUES ('01', 1, DEFAULT, 'г.Чита и Читинский');


INSERT INTO DEVICES_CONTROL.ROLES (ID, DESCRIPTION, NAME)
VALUES (DEFAULT, 'Администратор', 'Role_Admin');

INSERT INTO DEVICES_CONTROL.ROLES (ID, DESCRIPTION, NAME)
VALUES (DEFAULT, 'Пользователь', 'Role_User');
